'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WillStrohl.Modules.OpenGraph

    Partial Public Class Settings

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''chkTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTitle As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''chkDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDescription As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvUrl As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revUrl As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''chkUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUrl As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocale As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboLocale As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rfvLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvLocale As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlImage As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''lblSiteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSiteName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSiteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSiteName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvSiteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSiteName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''chkSiteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSiteName As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rfvType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblFacebookAdmins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFacebookAdmins As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFacebookAdmins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFacebookAdmins As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''revFacebookAdmins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revFacebookAdmins As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblFacebookAppId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFacebookAppId As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFacebookAppId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFacebookAppId As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''revFacebookAppId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revFacebookAppId As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDebug As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDebug As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lnkSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSubmit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkDisable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkDisable As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkClearSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkClearSettings As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace