'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WillStrohl.Modules.ContentSlider
    
    Partial Public Class SliderOptions
        
        '''<summary>
        '''lblWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWidth As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeight As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSpeed As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpeed As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSpeed As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''revSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revSpeed As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''lblFit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFit As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkFit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFit As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblContainerResize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContainerResize As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkContainerResize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkContainerResize As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblPause control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPause As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkPause control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPause As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblExcludeCycle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExcludeCycle As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkExcludeCycle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkExcludeCycle As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblExcludeEasing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExcludeEasing As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkExcludeEasing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkExcludeEasing As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCacheDuration As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCacheDuration As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCacheDuration As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''revCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revCacheDuration As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''lblCssAfter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCssAfter As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCssAfter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCssAfter As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblCssBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCssBefore As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCssBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCssBefore As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblEasing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEasing As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEasing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEasing As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblEaseIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEaseIn As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEaseIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEaseIn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblEaseOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEaseOut As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEaseOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEaseOut As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPager As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPager As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblActivePagerClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActivePagerClass As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtActivePagerClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActivePagerClass As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblPagerAnchorBuilder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPagerAnchorBuilder As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtPagerAnchorBuilder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPagerAnchorBuilder As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lnkDefaultPagerAnchorBuilder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkDefaultPagerAnchorBuilder As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lblNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNext As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNext As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblPrev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrev As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtPrev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrev As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblPauseOnPagerHover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPauseOnPagerHover As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkPauseOnPagerHover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPauseOnPagerHover As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblAllowPagerClickBubble control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowPagerClickBubble As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkAllowPagerClickBubble control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowPagerClickBubble As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblAutoStop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoStop As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkAutoStop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoStop As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblAutoStopCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoStopCount As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtAutoStopCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAutoStopCount As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblBackwards control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBackwards As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkBackwards control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBackwards As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblMetaAttr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMetaAttr As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtMetaAttr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMetaAttr As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvMetaAttr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvMetaAttr As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblNoWrap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoWrap As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkNoWrap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNoWrap As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblRandom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRandom As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkRandom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRandom As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblRequeueOnImageNotLoaded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequeueOnImageNotLoaded As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkRequeueOnImageNotLoaded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequeueOnImageNotLoaded As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblRequeueTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequeueTimeout As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtRequeueTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRequeueTimeout As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvRequeueTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvRequeueTimeout As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''revRequeueTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revRequeueTimeout As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''lblShuffle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShuffle As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtShuffle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtShuffle As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblSlideResize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSlideResize As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkSlideResize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideResize As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblStartingSlide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartingSlide As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtStartingSlide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartingSlide As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblAnimIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnimIn As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtAnimIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnimIn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblAnimOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnimOut As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtAnimOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnimOut As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblContinuous control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContinuous As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkContinuous control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkContinuous As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDelay As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDelay As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblFastOnEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFastOnEvent As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtFastOnEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFastOnEvent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblFx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFx As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''cboFx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFx As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rfvFx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvFx As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblManualTrump control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManualTrump As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkManualTrump control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkManualTrump As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblRandomizeEffects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRandomizeEffects As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkRandomizeEffects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRandomizeEffects As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblRev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRev As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkRev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRev As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblSpeedIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSpeedIn As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtSpeedIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpeedIn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblSpeedOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSpeedOut As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtSpeedOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpeedOut As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeout As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeout As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTimeout As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblSync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSync As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkSync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSync As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblAfter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAfter As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtAfter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAfter As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBefore As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBefore As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnd As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEnd As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblFxFn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFxFn As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtFxFn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFxFn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblOnPagerEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnPagerEvent As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtOnPagerEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnPagerEvent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblOnPrevNextEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnPrevNextEvent As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtOnPrevNextEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnPrevNextEvent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblPagerEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPagerEvent As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtPagerEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPagerEvent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvPagerEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPagerEvent As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblPrevNextEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrevNextEvent As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtPrevNextEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrevNextEvent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvPrevNextEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPrevNextEvent As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''lblSlideExpr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSlideExpr As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtSlideExpr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSlideExpr As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblTimeoutFn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeoutFn As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtTimeoutFn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeoutFn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblUpdateActivePagerLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdateActivePagerLink As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtUpdateActivePagerLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUpdateActivePagerLink As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lnkSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lnkCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lnkReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkReset As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
