'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WillStrohl.Modules.Lightbox

    Partial Public Class EditLightbox

        '''<summary>
        '''vsError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vsError As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''lblGalleryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGalleryName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtGalleryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGalleryName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvGalleryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvGalleryName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblGalleryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGalleryDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtGalleryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGalleryDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvGalleryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvGalleryDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblGalleryFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGalleryFolder As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboGalleryFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboGalleryFolder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvGalleryFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvGalleryFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblHideTitleDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHideTitleDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideTitleDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTitleDescription As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPadding As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPadding As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPadding As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPadding As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMargin As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMargin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvMargin As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revMargin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revMargin As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOpacity As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOpacity As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblModal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModal As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkModal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkModal As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblCyclic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCyclic As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCyclic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCyclic As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblOverlayShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverlayShow As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkOverlayShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOverlayShow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblOverlayOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverlayOpacity As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOverlayOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOverlayOpacity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvOverlayOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvOverlayOpacity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revOverlayOpacity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revOverlayOpacity As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblOverlayColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverlayColor As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOverlayColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOverlayColor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvOverlayColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvOverlayColor As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblTitleShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleShow As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkTitleShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTitleShow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTitlePosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitlePosition As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstTitlePosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTitlePosition As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''rfvTitlePosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTitlePosition As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblTransition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTransition As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstTransition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTransition As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''rfvTransition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvTransition As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSpeed As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSpeed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSpeed As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revSpeed As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblChangeSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChangeSpeed As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtChangeSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChangeSpeed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvChangeSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvChangeSpeed As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revChangeSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revChangeSpeed As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblShowCloseButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowCloseButton As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowCloseButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowCloseButton As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblShowNavArrows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowNavArrows As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowNavArrows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowNavArrows As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEnableEscapeButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnableEscapeButton As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableEscapeButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableEscapeButton As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblOnStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnStart As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOnStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnStart As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnCancel As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnCancel As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOnComplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnComplete As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOnComplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnComplete As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOnCleanup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnCleanup As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOnCleanup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnCleanup As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOnClosed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnClosed As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtOnClosed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOnClosed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteThumbnails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteThumbnails As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''hdnGalleryFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnGalleryFolder As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
