'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WillStrohl.Modules.ContactCollector

    Partial Public Class Settings

        '''<summary>
        '''lblRequiredFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequiredFields As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkRequiredFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequiredFields As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblComment As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkComment As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblUseCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUseCaptcha As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseCaptcha As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblSendEmailToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSendEmailToContact As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSendEmailToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSendEmailToContact As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEmailSubjectToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailSubjectToContact As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailSubjectToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailSubjectToContact As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmailMessageToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailMessageToContact As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailMessageToContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailMessageToContact As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''lblSendEmailToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSendEmailToAdmin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSendEmailToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSendEmailToAdmin As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblEmailSubjectToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailSubjectToAdmin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailSubjectToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailSubjectToAdmin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmailMessageToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailMessageToAdmin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailMessageToAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailMessageToAdmin As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''lblAdminEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAdminEmail As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAdminEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAdminEmail As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
